/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administradordeseries.vista.principal;

import administradordeseries.controlador.SerieControlador;
import administradordeseries.enums.Genero;
import administradordeseries.modelo.SerieModelo;
import administradordeseries.vista.basededatos.ConexionBaseDatos;
import administradordeseries.vista.serie.AgregarSerie;
import administradordeseries.vista.serie.ModificarSerie;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author benja
 */
public class Principal extends javax.swing.JFrame {

    SerieControlador serieControlador = new SerieControlador();
    ConexionBaseDatos conexionBaseDatos;

    public Principal(ConexionBaseDatos conexionBaseDatos) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargarSeries();

        buscarGenero.addItem(null);
        for (Genero value : Genero.values()) {
            buscarGenero.addItem(value.toString());
        }

        buscarEstrella.addItem("");
        for (int i = 0; i < 5; i++) {
            buscarEstrella.addItem(1 + i + "");
        }
        this.conexionBaseDatos = conexionBaseDatos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTSeries = new javax.swing.JTable();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBAgregar = new javax.swing.JButton();
        jBAnular = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buscarTitulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBConsultar = new javax.swing.JButton();
        rbmcien = new javax.swing.JRadioButton();
        rbmquinientos = new javax.swing.JRadioButton();
        rbmmil = new javax.swing.JRadioButton();
        rbmamil = new javax.swing.JRadioButton();
        buscarEstrella = new javax.swing.JComboBox<>();
        buscarGenero = new javax.swing.JComboBox<>();
        cbATP = new java.awt.Checkbox();

        jButton6.setText("jButton2");

        jButton11.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTSeries.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTSeries);

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jBAgregar.setText("Agregar");
        jBAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jBAnular.setText("Anular");
        jBAnular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnularActionPerformed(evt);
            }
        });

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRADOR DE SERIES");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        jBRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 620, Short.MAX_VALUE)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jBRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BUSCAR SERIE");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Genero:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Estrellas:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Titulo:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Precio:");

        jBConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jBConsultar.setText("Consultar");
        jBConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbmcien);
        rbmcien.setText("Menor a 100");

        buttonGroup1.add(rbmquinientos);
        rbmquinientos.setText("Menor a 500");

        buttonGroup1.add(rbmmil);
        rbmmil.setText("Menor a 1000");

        buttonGroup1.add(rbmamil);
        rbmamil.setText("Mayor a 1000");
        rbmamil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmamilActionPerformed(evt);
            }
        });

        buscarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarGeneroActionPerformed(evt);
            }
        });

        cbATP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbATP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cbATP.setLabel("ATP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbATP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(rbmcien)
                    .addComponent(rbmquinientos)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbmmil)
                            .addComponent(rbmamil)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buscarTitulo)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(buscarEstrella, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarEstrella, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cbATP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbmcien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbmquinientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbmmil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbmamil)
                .addGap(34, 34, 34)
                .addComponent(jBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        AgregarSerie agregarSerie = new AgregarSerie(this);
        agregarSerie.setVisible(true);
        agregarSerie.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        SerieModelo serieModelo = new SerieModelo();

        int fila = jTSeries.getSelectedRow();

        if (fila != -1) {
            String estado = jTSeries.getValueAt(fila, 8).toString();
            if (estado.equals("AC")) {
                String precio = eliminarSignoPeso((jTSeries.getValueAt(fila, 6).toString()));
                String fecha = jTSeries.getValueAt(fila, 3).toString();
                serieModelo.setId(Long.parseLong(jTSeries.getValueAt(fila, 0).toString()));
                serieModelo.setTitulo(jTSeries.getValueAt(fila, 1).toString());
                serieModelo.setDescripcion(jTSeries.getValueAt(fila, 2).toString());

                try {
                    serieModelo.setFechaEstreno(convertirACalendar(fecha));
                } catch (ParseException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }

                serieModelo.setEstrellas(Integer.parseInt(jTSeries.getValueAt(fila, 4).toString()));
                serieModelo.setGenero(Genero.valueOf((jTSeries.getValueAt(fila, 5).toString())));
                serieModelo.setPrecioAlquiler(Double.parseDouble(precio));
                serieModelo.setAtp("Si".equals(jTSeries.getValueAt(fila, 7).toString()));
                serieModelo.setEstado(jTSeries.getValueAt(fila, 8).toString());

                ModificarSerie modificarSerie = new ModificarSerie(this);

                modificarSerie.setVisible(true);
                modificarSerie.establecerDatosForm(serieModelo);
                modificarSerie.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            } else {
                JOptionPane.showMessageDialog(null, "No se puede modificar una serie anulada");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una serie de la lista por favor");
        }


    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        int fila = jTSeries.getSelectedRow();

        if (fila != -1) {
            Long id = Long.parseLong(jTSeries.getValueAt(fila, 0).toString());
            String nombre = jTSeries.getValueAt(fila, 1).toString();

            int rsp = JOptionPane.showConfirmDialog(null,
                    "¿Seguro desea elimnar la serie " + nombre + " ?", "Advertencia!!", JOptionPane.WARNING_MESSAGE);
            {
                if (rsp == 0) {
                    try {
                        boolean respuesta = serieControlador.eliminar(id);
                        JOptionPane.showMessageDialog(null, "Se eliminó correctamente la serie", "Exito", JOptionPane.INFORMATION_MESSAGE);
                        cargarSeries();
                    } catch (Exception ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "No fue posible eliminar la serie");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un item de la lista");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnularActionPerformed
        int fila = jTSeries.getSelectedRow();

        if (fila != -1) {

            Long id = Long.parseLong(jTSeries.getValueAt(fila, 0).toString());
            String nombre = jTSeries.getValueAt(fila, 1).toString();
            try {
                int rsp = JOptionPane.showConfirmDialog(null,
                        "¿Seguro desea anular la serie ?", "Advertencia!!", JOptionPane.WARNING_MESSAGE);
                {
                    if (rsp == 0) {
                        try {
                            serieControlador.anular(id);
                            JOptionPane.showMessageDialog(null, "Se anulo correctamente la serie " + nombre, "Exito", JOptionPane.INFORMATION_MESSAGE);
                            cargarSeries();
                        } catch (Exception ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(null, "No fue posible anular la serie");
                        }
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un item de la lista");
        }
    }//GEN-LAST:event_jBAnularActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        Genero genero;
        Integer estrellas;
        String titulo;

        try {
            estrellas = Integer.parseInt(buscarEstrella.getItemAt(buscarEstrella.getSelectedIndex()));
        } catch (Exception e) {
            estrellas = null;
        }
        try {
            titulo = buscarTitulo.getText();
        } catch (Exception e) {
            titulo = null;
        }
        try {
            genero = (Genero.valueOf(buscarGenero.getSelectedItem().toString()));
            if (genero.toString().isEmpty() || genero.toString().equals("")) {
                genero = null;
            }
        } catch (Exception e) {
            genero = null;
        }

        boolean atp = cbATP.getState();

        boolean menorcien = false;
        boolean menorquinientos = false;
        boolean menormil = false;
        boolean mayorMil = false;

        if (rbmcien.isSelected()) {
            menorcien = true;
        } else if (rbmquinientos.isSelected()) {
            menorquinientos = true;
        } else if (rbmmil.isSelected()) {
            menormil = true;
        } else if (rbmamil.isSelected()) {
            mayorMil = true;
        }

        mostrarConsulta(titulo, genero, estrellas, atp, menorcien, menorquinientos, menormil, mayorMil);


    }//GEN-LAST:event_jBConsultarActionPerformed

    private void rbmamilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmamilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmamilActionPerformed

    private void buscarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarGeneroActionPerformed

    private void jBRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefreshActionPerformed
        limpiarConsulta();
        cargarSeries();
    }//GEN-LAST:event_jBRefreshActionPerformed

    public final void cargarSeries() {

        String[] columNames = {"id", "titulo", "Descripcion", "Fecha Estreno", "Estrellas", "Genero", "Precio Alquiler", "ATP", "Estado"};
        DefaultTableModel model = new DefaultTableModel(null, columNames) {

            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }

        };

        List<SerieModelo> series = serieControlador.listar();

            for (SerieModelo serie : series) {
                Object[] data = new Object[columNames.length];

                Calendar cal = serie.getFechaEstreno();

                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                data[0] = serie.getId();
                data[1] = serie.getTitulo();
                data[2] = serie.getDescripcion();
                data[3] = sdf.format(cal.getTime());
                data[4] = serie.getEstrellas();
                data[5] = serie.getGenero();
                data[6] = "$" + serie.getPrecioAlquiler();
                data[7] = serie.isAtp() == true ? "SI" : "NO";
                data[8] = serie.getEstado();

                model.addRow(data);
        }

        jTSeries.setModel(model);
    }

    private void mostrarConsulta(String titulo, Genero genero, Integer estrellas,
            boolean atp, boolean menorCien, boolean menorQuinientos,
            boolean menorMil, boolean mayorMil) {

        String[] columNames = {"id", "titulo", "Descripcion", "Fecha Estreno", "Estrellas", "Genero", "Precio Alquiler", "ATP", "Estado"};
        DefaultTableModel model = new DefaultTableModel(null, columNames) {

            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }

        };

        List<SerieModelo> series = serieControlador.consultar(titulo, genero, estrellas, atp, menorCien, menorQuinientos, menorMil, mayorMil);

        series.forEach((serie) -> {
            Object[] data = new Object[columNames.length];

            Calendar cal = serie.getFechaEstreno();

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            data[0] = serie.getId();
            data[1] = serie.getTitulo();
            data[2] = serie.getDescripcion();
            data[3] = sdf.format(cal.getTime());
            data[4] = serie.getEstrellas();
            data[5] = serie.getGenero();
            data[6] = "$" + serie.getPrecioAlquiler();
            data[7] = serie.isAtp() == true ? "SI" : "NO";
            data[8] = serie.getEstado();

            model.addRow(data);
        });

        jTSeries.setModel(model);
    }

    private void limpiarConsulta() {

        buscarEstrella.setSelectedIndex(0);
        buscarGenero.setSelectedIndex(0);
        buscarTitulo.setText("");
        cbATP.setState(false);
        rbmamil.setSelected(false);
        rbmcien.setSelected(false);
        rbmmil.setSelected(false);
        rbmquinientos.setSelected(false);
    }

    private String eliminarSignoPeso(String cadena) {
        return cadena.replace("$", "");
    }

    private Calendar convertirACalendar(String fecha) throws ParseException {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date dataFormateada = formato.parse(fecha);

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(dataFormateada);

        return calendar;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> buscarEstrella;
    private javax.swing.JComboBox<String> buscarGenero;
    private javax.swing.JTextField buscarTitulo;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Checkbox cbATP;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBAnular;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBRefresh;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTSeries;
    private javax.swing.JRadioButton rbmamil;
    private javax.swing.JRadioButton rbmcien;
    private javax.swing.JRadioButton rbmmil;
    private javax.swing.JRadioButton rbmquinientos;
    // End of variables declaration//GEN-END:variables
}
